
-- --------------------------------------------------------

--
-- Structure for view `admin_dai_luar`
--
DROP TABLE IF EXISTS `admin_dai_luar`;

DROP VIEW IF EXISTS `admin_dai_luar`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `admin_dai_luar`  AS SELECT `dt_layanan`.`id` AS `id_layanan`, `dt_layanan`.`keterangan` AS `keterangan`, `dt_layanan`.`id_stat` AS `id_stat`, `dt_layanan`.`jenis_layanan` AS `jenis_layanan`, `dt_kegiatan`.`nm_keg` AS `nm_keg`, date_format(`dt_kegiatan`.`tgl_awal_keg`,'%d %M %Y') AS `tgl_awal_keg`, `mt_status_layanan`.`nama_stat` AS `nama_stat`, `dt_layanan`.`alasan_tolak` AS `alasan_tolak`, lpad(`mt_direktorat`.`id`,2,0) AS `no_direktorat`, lpad(`mt_layanan`.`id`,2,0) AS `no_layanan`, lpad(`dt_layanan`.`id`,4,0) AS `no_urut`, date_format(`dt_layanan`.`syscreatedate`,'%d %M %Y') AS `tgl_daftar`, date_format(`dt_layanan`.`sysupdatedate`,'%d %M %Y') AS `tgl_proses`, (to_days(`dt_layanan`.`sysupdatedate`) - to_days(`dt_layanan`.`syscreatedate`)) AS `lama`, date_format(`dt_layanan`.`syscreatedate`,'%m.%Y') AS `tgl_input` FROM (((((`dt_layanan_dokumen` left join (`dt_penceramah` left join (`dt_kegiatan` left join (`mt_direktorat` left join (`mt_layanan` left join (`mt_status_layanan` left join (`sys_users` left join `dt_layanan` on((`dt_layanan`.`id_user` = `sys_users`.`id`))) on((`dt_layanan`.`id_stat` = `mt_status_layanan`.`id`))) on((`dt_layanan`.`jenis_layanan` = `mt_layanan`.`id`))) on((`mt_layanan`.`jenis_layanan` = `mt_direktorat`.`id`))) on((`dt_kegiatan`.`id_layanan` = `dt_layanan`.`id`))) on((`dt_penceramah`.`id_layanan` = `dt_layanan`.`id`))) on((`dt_layanan`.`id` = `dt_layanan_dokumen`.`id_layanan`))) left join `mt_wil_provinsi` on((`dt_layanan`.`id_provinsi` = `mt_wil_provinsi`.`id_provinsi`))) left join `mt_wil_kabupaten` on(((`dt_layanan`.`id_kabupaten` = `mt_wil_kabupaten`.`id_kabupaten`) and (`mt_wil_kabupaten`.`id_provinsi` = `mt_wil_provinsi`.`id_provinsi`)))) left join `mt_wil_kecamatan` on(((`dt_layanan`.`id_kecamatan` = `mt_wil_kecamatan`.`id_kecamatan`) and (`mt_wil_kecamatan`.`id_kabupaten` = `mt_wil_kabupaten`.`id_kabupaten`)))) left join `mt_wil_kelurahan` on(((`dt_layanan`.`id_kelurahan` = `mt_wil_kelurahan`.`id_kelurahan`) and (`mt_wil_kelurahan`.`id_kecamatan` = `mt_wil_kecamatan`.`id_kecamatan`)))) GROUP BY `dt_layanan`.`id` ORDER BY `dt_kegiatan`.`tgl_awal_keg` ASC ;
