
-- --------------------------------------------------------

--
-- Structure for view `admin_lkspwu`
--
DROP TABLE IF EXISTS `admin_lkspwu`;

DROP VIEW IF EXISTS `admin_lkspwu`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `admin_lkspwu`  AS SELECT `dt_layanan`.`stat` AS `status_aktif`, `dt_layanan`.`jenis_layanan` AS `jenis_layanan`, `dt_layanan`.`id_stat` AS `id_stat`, `dt_layanan`.`id` AS `id_layanan`, lpad(`mt_direktorat`.`id`,2,0) AS `no_direktorat`, lpad(`mt_layanan`.`id`,2,0) AS `no_layanan`, date_format(`dt_layanan`.`syscreatedate`,'%m.%Y') AS `tgl_input`, lpad(`dt_layanan`.`id`,4,0) AS `no_urut`, `sys_users`.`fullname` AS `fullname`, `sys_users`.`email` AS `email`, `sys_users`.`telp` AS `telp`, `dt_instansi`.`nm_instansi` AS `nm_instansi`, `dt_instansi`.`email_instansi` AS `email_instansi`, `dt_instansi`.`telp_instansi` AS `telp_instansi`, date_format(`dt_layanan`.`syscreatedate`,'%d %M %Y') AS `tgl_daftar`, `mt_status_layanan`.`nama_stat` AS `nama_stat` FROM ((((((((((((((`dt_layanan` join `sys_users` on((`dt_layanan`.`id_user` = `sys_users`.`id`))) join `dt_instansi` on((`dt_layanan`.`id` = `dt_instansi`.`id_layanan`))) left join `mt_wil_provinsi` `prov_instansi` on((`dt_instansi`.`id_provinsi` = `prov_instansi`.`id_provinsi`))) left join `mt_wil_kabupaten` `kab_instansi` on((`dt_instansi`.`id_kabupaten` = `kab_instansi`.`id_kabupaten`))) left join `mt_wil_kecamatan` `kec_instansi` on((`dt_instansi`.`id_kecamatan` = `kec_instansi`.`id_kecamatan`))) left join `mt_wil_kelurahan` `kel_instansi` on((`dt_instansi`.`id_kelurahan` = `kel_instansi`.`id_kelurahan`))) left join `mt_wil_provinsi` `prov_user` on((`dt_layanan`.`id_provinsi` = `prov_user`.`id_provinsi`))) left join `mt_wil_kabupaten` `kab_user` on((`dt_layanan`.`id_kabupaten` = `kab_user`.`id_kabupaten`))) left join `mt_wil_kecamatan` `kec_user` on((`dt_layanan`.`id_kecamatan` = `kec_user`.`id_kecamatan`))) left join `mt_wil_kelurahan` `kel_user` on((`dt_layanan`.`id_kelurahan` = `kel_user`.`id_kelurahan`))) join `dt_layanan_dokumen` on((`dt_layanan`.`id` = `dt_layanan_dokumen`.`id_layanan`))) join `mt_layanan` on((`dt_layanan`.`jenis_layanan` = `mt_layanan`.`id`))) join `mt_direktorat` on((`mt_layanan`.`jenis_layanan` = `mt_direktorat`.`id`))) join `mt_status_layanan` on((`dt_layanan`.`id_stat` = `mt_status_layanan`.`id`))) ;
