
-- --------------------------------------------------------

--
-- Structure for view `detail_izin_kegiatan_keagamaan`
--
DROP TABLE IF EXISTS `detail_izin_kegiatan_keagamaan`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `detail_izin_kegiatan_keagamaan`  AS SELECT `sys_users`.`fullname` AS `nama_user`, `sys_users`.`nik` AS `nik`, `sys_users`.`tgl_lhr` AS `tgl_lhr`, `sys_users`.`telp` AS `telp`, `sys_users`.`email` AS `mail`, `dt_kegiatan`.`nm_keg` AS `nm_keg`, `dt_kegiatan`.`tgl_akhir_keg` AS `tgl_akhir_keg`, `dt_kegiatan`.`tgl_awal_keg` AS `tgl_awal_keg`, `dt_kegiatan`.`lemb_keg` AS `lemb_keg`, `dt_kegiatan`.`esti_keg` AS `esti_keg`, `dt_kegiatan`.`alamat_keg` AS `alamat_keg`, `dt_penceramah`.`narsum` AS `narsum`, `mt_wil_provinsi`.`nama` AS `provinsi`, `mt_wil_kabupaten`.`nama` AS `kabupaten`, `mt_wil_kecamatan`.`nama` AS `kecamatan`, `mt_wil_kelurahan`.`nama` AS `kelurahan`, `dt_layanan`.`keterangan` AS `keterangan`, `dt_layanan`.`id` AS `id_layanan`, `dt_layanan`.`id_stat` AS `stat_id`, `dt_layanan_dokumen`.`proposal_keg` AS `proposal_keg`, `dt_layanan_dokumen`.`surat_permohonan_keg` AS `surat_permohonan_keg`, `dt_layanan_dokumen`.`ktp_keg` AS `ktp_keg`, lpad(`mt_direktorat`.`id`,2,0) AS `no_direktorat`, lpad(`mt_layanan`.`id`,2,0) AS `no_layanan`, lpad(`dt_layanan`.`id`,4,0) AS `no_urut`, date_format(`dt_layanan`.`syscreatedate`,'%m.%Y') AS `tgl_input`, `dt_layanan`.`alasan_tolak` AS `alasan_tolak` FROM (((((`dt_layanan_dokumen` left join (`dt_penceramah` left join (`dt_kegiatan` left join (`mt_direktorat` left join (`mt_layanan` left join (`mt_status_layanan` left join (`sys_users` left join `dt_layanan` on((`dt_layanan`.`id_user` = `sys_users`.`id`))) on((`dt_layanan`.`id_stat` = `mt_status_layanan`.`id`))) on((`dt_layanan`.`jenis_layanan` = `mt_layanan`.`id`))) on((`mt_layanan`.`jenis_layanan` = `mt_direktorat`.`id`))) on((`dt_kegiatan`.`id_layanan` = `dt_layanan`.`id`))) on((`dt_penceramah`.`id_layanan` = `dt_layanan`.`id`))) on((`dt_layanan`.`id` = `dt_layanan_dokumen`.`id_layanan`))) left join `mt_wil_provinsi` on((`dt_layanan`.`id_provinsi` = `mt_wil_provinsi`.`id_provinsi`))) left join `mt_wil_kabupaten` on(((`dt_layanan`.`id_kabupaten` = `mt_wil_kabupaten`.`id_kabupaten`) and (`mt_wil_kabupaten`.`id_provinsi` = `mt_wil_provinsi`.`id_provinsi`)))) left join `mt_wil_kecamatan` on(((`dt_layanan`.`id_kecamatan` = `mt_wil_kecamatan`.`id_kecamatan`) and (`mt_wil_kecamatan`.`id_kabupaten` = `mt_wil_kabupaten`.`id_kabupaten`)))) left join `mt_wil_kelurahan` on(((`dt_layanan`.`id_kelurahan` = `mt_wil_kelurahan`.`id_kelurahan`) and (`mt_wil_kelurahan`.`id_kecamatan` = `mt_wil_kecamatan`.`id_kecamatan`)))) ;
